### ISSUE TITLE
Write some unit tests

### ISSUE THREAD

**Issue by dbolser** [lastz/lastz#1]
Currently seems like there are none?

**Comment by lastz** [comment]
(Sorry for the delay in replying, for some reason github isn't sending me notifications for this repo)

You are (mostly) correct, there currently is only one small unit test in the repo.  I *do* have several that I used in my development, but neglected to add them to the repo.  My initial view of the repo was that it would be a copy of the distribution tarball.

I'll (probably) add the rest here, at some point.  But I can't estimate when that will happen.

**Comment by dbolser** [comment]
Thanks,​

**Comment by rsharris** [comment]
The latest commits to the main branch add a dozen or so unit tests.

This change is not yet in a tagged release, but should be, soon.

**Comment by rsharris** [comment]
The new tagged release 1.04.03 contains the unit tests.
