### ISSUE TITLE
Multiple Genome alignment

### ISSUE THREAD

**Issue by LemoAlex** [lastz/lastz#24]
Dear Lastz users,

I am trying to align ~20-30 genomes of moderate size (1-2GB) together. I was able to run the basic command line for pairwise alignments, but I have some questions about the general use of lastZ and multiple genome alignments.

From what I understand, I have to first perform the pairwise alignment using lastZ to obtain all the pairwise alignment wich I can afterwards combine (using multiZ for instance).
I wanted however to know if there was a way to automate the pairwise alignment, or if there was an option in lastZ to directly perform the multiple genome alignment by providing all the genomes in the input? (Similar to, e.g. Mauve) Otherwise, it seems very time-consuming to run all the pairwise alignement manually. 

Finally, I was also wondering whether there was a possibility of aligning a whole genome to a previously obtained multiple genome alignment (in Maf format for instance) ?

Thanks for your help,

Alex

**Comment by rsharris** [comment]
Lastz doesn't directly support multiple alignment. I recommend cactus from Benedict Paten's group, https://github.com/ComparativeGenomicsToolkit/cactus. Be aware that it does perform all (or many of) the lastz pairwise alignments so it will still be computationally intense.

You should also consider https://github.com/medvedevgroup/SibeliaZ from Ilia Minkin. This treats the collection of genomes en masse, creating a deBruijn graph, identifying homologous regions from that, then using another tool (SPOA, I think) to generate base-by-base multiple alignments separately in each homologous region. I think Ilia's text case was 16 strains of mice, which sounds similar to your problem (though you might have higher divergence than that).

Also look at the 2014 Alignathon paper (Dent et al, Genome Research) that compared roughly a dozen multiple aligners. My take from that paper is that cactus and one of the multiz variants performed very similarly. I've found that cactus is better documented that multiz, though I some systems I've been unable to install all the dependencies cactus requires.

As for aligning a genome to an existing multiple alignment, the short answer is that lastz doesn't provide an easy solution for this. The cactus package certainly is doing this internally, so you may want to contact the authors to see if they have exposed an interface to do that.

Hope that helps,
Bob H
