### ISSUE TITLE
Build Fail (v1.04.12)

### ISSUE THREAD

**Issue by rmandla** [lastz/lastz#40]
Hi,

I am trying to build lastz straight from the code on GitHub, but I am getting a makefile error:

$ make

`gcc -c -O3 -Wall -Wextra -Werror -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DVERSION_MAJOR="\"1"\" -DVERSION_MINOR="\"04"\" -DVERSION_SUBMINOR="\"12"\" -DREVISION_DATE="\"20210209"\" -DSUBVERSION_REV="\""\" -Dscore_type=\'I\' lastz.c -o lastz.o
lastz.c: In function ‘parse_options.constprop’:
lastz.c:9070:43: error: ‘maxScore’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
 9070 |     lzParams->ballScore = ballScoreFactor * maxScore
      |                           ~~~~~~~~~~~~~~~~^~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:94: lastz.o] Error 1`

I can build from version 1.04.03 if I copy the sequences.c file from GitHub to src, as you previously mentioned in other issues.

Thanks!

**Comment by rsharris** [comment]
The compiler wasn't able to figure out that maxScore had been initialized in all cases that would reach that line. I've verified that it will always will have been initialized, so this error is benign.

I've pushed a modification for that, so the compiler should know that the maxScore has been initialized. You can use by pulling or downloading the latest code from the repo.

An alternate solution is to modify the Makefile, around like 57, and remove "-Werror". This is the compiler flag that turns warnings into errors. You would still see this reported (possibly with other issues), but the compiler should then complete the build. You would have to decide whether any warnings were benign or not (of course you could report them here).

Thanks for reporting that. Compilers have gotten smarter about suspicious code over the past decade. Nearly all of these warnings/errors end up being benign. But IIRC there's been at least one that wasn't.

**Comment by rmandla** [comment]
Thanks!
