### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by aderzelle** [lastz/lastz#5]
Hello,
attempting to compile lastz from source on Manjaro Linux returns the following
```
make[1]: *** [Makefile:94: lastz.o] Error 1
make[1]: Leaving directory '/home/alessandro/tools/lastz/src'
make: *** [Makefile:14: build_lastz] Error 2

```
I am using `gcc version 7.1.1 20170516 (GCC)`

Thank you

**Comment by lastz** [comment]
(Sorry for the delay in replying, for some reason github isn't sending me notifications for this repo)

There's not enough information there to solve the problem.  Apparently the compiler wasn't able to successfully compile lastz, and it probably reported why earlier in the output (i.e. before the first line you posted).

My best guess would be that your compiler found something suspicious in the source code, most likely benign.  The build process is set up to treat compiler warnings as errors, as described in the docs here (4th paragraph in the "Installation" section):
    http://www.bx.psu.edu/~rsharris/lastz/README.lastz-1.04.00.html#install

**Comment by dwinter** [comment]
This is very likely the same error I get with `gcc version 6.3.0 `

```
cd src && make lastz lastz_D
make[1]: Entering directory '/home/david/src/lastz/src'
gcc -c -O3 -Wall -Wextra -Werror -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DVERSION_MAJOR="\"1"\" -DVERSION_MINOR="\"04"\" -DVERSION_SUBMINOR="\"00"\" -DREVISION_DATE="\"20170312"\" -DSUBVERSION_REV="\"1881:1893M"\" -Dscore_type=\'I\' lastz.c -o lastz.o
lastz.c: In function ‘parse_options_loop’:
lastz.c:6525:6: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
      if (*scan != '.') goto cant_understand;  scan++;
      ^~
lastz.c:6525:47: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
      if (*scan != '.') goto cant_understand;  scan++;
                                               ^~~~
lastz.c:6585:6: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
      if (*scan != '.') goto cant_understand;  scan++;
      ^~
lastz.c:6585:47: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
      if (*scan != '.') goto cant_understand;  scan++;
                                               ^~~~
lastz.c:6644:6: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
      if (*scan != '.') goto cant_understand;  scan++;
      ^~
lastz.c:6644:47: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
      if (*scan != '.') goto cant_understand;  scan++;
                                               ^~~~
cc1: all warnings being treated as errors
Makefile:94: recipe for target 'lastz.o' failed
make[1]: *** [lastz.o] Error 1
make[1]: Leaving directory '/home/david/src/lastz/src'
Makefile:14: recipe for target 'build_lastz' failed
make: *** [build_lastz] Error 2
```

You can get around this by deleting `Werror` from the CFLAGS listed in definedForAll in `src/Makefile` (overriding CFLAGS from the command line just causing new errors).

**Comment by rsharris** [comment]
@dwinter Thanks for posting that.

I've checked that the code this is warning about is benign.  I will modify the source code whenever I make the next release (but this is unlikely to be soon).

Your workaround is the one I recommend.

**Comment by rsharris** [comment]
The latest commits to the main branch modify the source code in a way that should avoid that warning.

This change is not yet in a tagged release, but should be, soon.
