### ISSUE TITLE
capsule file error

### ISSUE THREAD

**Issue by nottwy** [lastz/lastz#9]
I used the command below to create capsule file:
`lastz_32 A.fna[multiple] --writecapsule=A.lastz.capsule --notransition --step=20 --nogapped`
Then I tried to use this capsule file like this:
`lastz_32 --targetcapsule=A.lastz.capsule 27.fa[multiple] --format=general:nmismatch,name1,strand1,start1,end1,name2,strand2,start2,end2`
And then the program give me the error message:
`FAILURE: bad capsule file (missing reverse sequence)`

**Comment by rsharris** [comment]
I am able reproduce that problem.

If you remove --nogapped from the original command, this appears to work.

If you don't want gapped alignments in your alignment output, you'll need to add --nogapped to that second command.  I think --notransition will also be needed for the second command.  I realize it's not obvious which options are relevant to capsulization and which aren't. 

This is definitely a bug. When --writecapsule is in the command line, options that aren't relevant to capsulization should either be ignored or reported to the user.

I don't have the bandwidth to look deeper into this for the next few days, though.

Thanks for reporting that,
Bob H

**Comment by nottwy** [comment]
After removing --nogapped, it works now.
3ku~
